const OPENAI='https://api.openai.com/v1/chat/completions';
const SHIPMENTS=['581742','936105','274869'];
const FINAL='Gracias a ti. Soy Carla, asistente de voz de Nexo Voice. Puedo atender llamadas, resolver consultas, consultar pedidos o expediciones, gestionar citas, recoger avisos y adaptar la atención a las necesidades de cada empresa. Nexo Voice se puede adaptar prácticamente a cualquier negocio. Si quieres verlo funcionando en el tuyo, podemos prepararte una demo personalizada.';
function fold(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9@.]+/g,' ').trim()}
function canonicalShipment(text){const raw=String(text||''),digits=raw.replace(/\D/g,'');for(const id of SHIPMENTS)if(digits.includes(id))return id;const t=fold(raw);const aliases={'581742':['cinco ocho uno siete cuatro dos','quinientos ochenta y un mil setecientos cuarenta y dos','cincuenta y ocho diecisiete cuarenta y dos'],'936105':['nueve tres seis uno cero cinco','novecientos treinta y seis mil ciento cinco','noventa y tres sesenta y uno cero cinco'],'274869':['dos siete cuatro ocho seis nueve','doscientos setenta y cuatro mil ochocientos sesenta y nueve','veintisiete cuarenta y ocho sesenta y nueve']};for(const [id,list] of Object.entries(aliases))if(list.some(a=>t.includes(a)))return id;return null}
function lastUser(ms){for(let i=(ms||[]).length-1;i>=0;i--)if(ms[i]?.role!=='assistant')return String(ms[i]?.text||ms[i]?.content||'');return ''}
function contextShipment(ms){for(let i=(ms||[]).length-1;i>=0;i--){const id=canonicalShipment(ms[i]?.text||ms[i]?.content||'');if(id)return id}return null}
function seenIds(ms){const set=new Set();for(const m of ms||[]){const id=canonicalShipment(m?.text||m?.content||'');if(id)set.add(id)}return set}
function deterministic(ms){const raw=lastUser(ms),t=fold(raw),direct=canonicalShipment(raw),ctx=direct||contextShipment((ms||[]).slice(0,-1)),seen=seenIds(ms);
 if(seen.size>=2&&/(gracias|muchas gracias|perfecto|hasta luego|adios|eso es todo)/.test(t))return {reply:FINAL,end_demo:true};
 if(!direct&&!ctx&&/(envio|expedicion|pedido|paquete)/.test(t))return {reply:'Claro. Dime el número de expedición y lo consulto.'};
 if(direct==='581742')return {reply:'Sí, lo tengo. Está en reparto en Valencia y no consta ninguna incidencia.'};
 if(direct==='936105')return {reply:'Sí, lo tengo. Sigue en tránsito hacia Málaga y no consta ninguna incidencia.'};
 if(direct==='274869')return {reply:'Sí, ya está en la delegación de destino de Sevilla.'};
 if(/(cuando|llega|hora|entrega)/.test(t)&&ctx==='581742')return {reply:'Está previsto para hoy, entre las cuatro y las siete de la tarde.'};
 if(/(llam|avis)/.test(t)&&/(antes|entrega)/.test(t))return {reply:'Sí, dejo anotada la solicitud para que te llamen antes de entregar, pendiente de confirmación de la agencia.'};
 if(/(tard|retras|pasado algo|incidencia|problema)/.test(t)&&ctx==='936105')return {reply:'No consta ninguna incidencia. El último movimiento fue en Córdoba a las seis y diez de la tarde y sigue en tránsito.'};
 if(/(correo|email|e mail)/.test(t)&&!/@/.test(raw))return {reply:'Claro. Dime el correo y te dejo preparada la información.'};
 if(/@/.test(raw))return {reply:'Perfecto, dejo preparada la información para que te la envíen por correo.'};
 if(/(sevilla|delegacion|destino)/.test(t)&&ctx==='274869')return {reply:'Sí, ya está en la delegación de destino de Sevilla.'};
 if(/(bulto|paquete)/.test(t)&&ctx==='274869')return {reply:'Sí, son tres bultos.'};
 if(/(bulto|paquete)/.test(t)&&ctx==='581742')return {reply:'Sí, son dos bultos.'};
 if(/(bulto|paquete)/.test(t)&&ctx==='936105')return {reply:'Es un solo bulto.'};return null}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'method_not_allowed'});const {messages=[]}=req.body||{};const fixed=deterministic(messages);if(fixed)return res.status(200).json(fixed);if(!process.env.OPENAI_API_KEY)return res.status(503).json({error:'openai_not_configured'});const clean=(Array.isArray(messages)?messages:[]).slice(-10).map(m=>({role:m.role==='assistant'?'assistant':'user',content:String(m.text||m.content||'').slice(0,420)}));const system=`Eres Alejandra, asistente telefónica de Transportes Nexo en una demo. IMPORTANTE: la llamada ya ha comenzado y ya te has presentado. No vuelvas a saludar, no vuelvas a presentarte y no preguntes de nuevo “¿en qué puedo ayudarte?”. Continúa exactamente desde el contexto de la conversación. Español de España, natural, profesional y una frase breve. Expediciones: 581742 Valencia, reparto hoy entre las cuatro y las siete de la tarde, dos bultos, sin incidencia. 936105 Málaga, tránsito, mañana entre las cuatro y las ocho de la tarde, un bulto, último movimiento Córdoba a las seis y diez de la tarde, sin incidencia. 274869 Sevilla, delegación de destino, mañana entre las nueve de la mañana y las dos de la tarde, tres bultos, sin incidencia. Nunca escribas horas con cifras ni inventes datos.`;try{const r=await fetch(OPENAI,{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-4.1-nano',temperature:.1,max_tokens:55,messages:[{role:'system',content:system},...clean]})});const d=await r.json();if(!r.ok)return res.status(502).json({error:'openai_failed'});let reply=d.choices?.[0]?.message?.content?.trim();if(!reply)return res.status(502).json({error:'empty_reply'});if(/^(hola|buenos dias|buenas|soy alejandra|en que puedo ayudarte)/i.test(fold(reply)))reply='Dime el número de expedición y lo consulto.';return res.status(200).json({reply})}catch(e){return res.status(500).json({error:'internal_error'})}}
